spring:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        open-in-view: false
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 20
                jdbc.batch_size: 20
                order_updates: true
                batch_versioned_data: true

    datasource:
        url: jdbc:h2:mem:best_restaurant_db
        username: user
        password: password
        

    jackson.visibility:
        field: any
        getter: none
        setter: none
        is-getter: none

logging:
    level:
        root: WARN
        com.gustaff_well.best_restaurant: DEBUG
        org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
    encoding:
        charset: UTF-8
        enabled: true
        force: true


springdoc.swagger-ui.path: /